name: Deploy docs
on: [push]
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: Ambiki/ambiki-packages
          TARGET_BRANCH: main
          BUILD_SCRIPT: yarn && yarn docs:build-safe
          BUILD_DIR: docs/.vuepress/dist
